apiVersion: v1
kind: Service
metadata:
  name: sthcometproxy
  namespace: alkis-azna
spec:
  selector:
    app: sthcometproxy
  clusterIP: 10.124.0.14
  ports:
  - protocol: TCP
    name: tcp
    port: 8667
    targetPort: 8667
