apiVersion: v1
kind: Service
metadata:
  name: cygnusproxy
  namespace: alkis-azna
spec:
  selector:
    app: cygnusproxy
  clusterIP: 10.4.3.122
  ports:
  - protocol: TCP
    port: 5052
    targetPort: 5052