apiVersion: v1
kind: Service
metadata:
  name: authzforce
  namespace: alkis-azna
spec:
  selector:
    app: authzforce #Match with deployment name
  clusterIP: 10.4.9.129
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080 #Has to match with the port of the pod