apiVersion: v1
kind: Service
metadata:
  name: authzforce
  namespace: alkis-azna
spec:
  selector:
    app: authzforce
  clusterIP: 10.124.0.6
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080