kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authzforce-volume-claim
  namespace: alkis-azna
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authzforce-ps-volume
  namespace: alkis-azna
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
   server: 35.207.148.14 #ip of the nfs server
   path: "/mnt/sharedfolder/iXenOnK8s"   #Where the code is stored on the nfs server