apiVersion: v1
kind: Service
metadata:
  name: orion
  namespace: alkis-azna
spec:
  selector:
    app: orion
  clusterIP: 10.4.2.63
  type: NodePort
  ports:
  - protocol: TCP
    port: 1026
    targetPort: 1026
    nodePort: 32001
