apiVersion: v1
kind: Service
metadata:
  name: noderedproxy
  namespace: alkis-azna
spec:
  selector:
    app: noderedproxy
  clusterIP: 10.124.0.8
  ports:
  - protocol: TCP
    port: 1881
    targetPort: 1881