apiVersion: v1
kind: Service
metadata:
  name: cygnus
  namespace: alkis-azna
spec:
  selector:
    app: cygnus
  clusterIP: 10.4.5.232
  ports:
  - protocol: TCP
    name: serviceport
    port: 5051
    targetPort: 5051
  - protocol: TCP
    name: apiport
    port: 5080
    targetPort: 5080