apiVersion: v1
kind: Service
metadata:
  name: api-cygnus
  namespace: alkis-azna
spec:
  selector:
    app: cygnus
  clusterIP: 10.124.0.16
  ports:
  - protocol: TCP
    name: apiport
    port: 5080
    targetPort: 5080