apiVersion: v1
kind: Service
metadata:
  name: cygnusproxy
  namespace: alkis-azna
spec:
  selector:
    app: cygnusproxy
  clusterIP: 10.124.0.5
  ports:
  - protocol: TCP
    name: tcp
    port: 5052
    targetPort: 5052