kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: queryingsensors-volume-claim
  namespace: alkis-azna
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#  name: queryingsensors-ps-volume
#  labels:
#    type: local
# spec:
#  storageClassName: manual
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: "/home/ubuntu/kostas/QueryingSensors"   #Where the code will be stored on a worker's path