apiVersion: v1
kind: Service
metadata:
  name: queryingsensorsproxy
  namespace: alkis-azna
spec:
  selector:
    app: queryingsensorsproxy
  clusterIP: 10.124.0.12
  ports:
  - protocol: TCP
    port: 1025
    targetPort: 1025