apiVersion: v1
kind: Service
metadata:
  name: queryingsensors
  namespace: alkis-azna
spec:
  selector:
    app: queryingsensors
  clusterIP: 10.4.8.217
  ports:
  - protocol: TCP
    port: 1024
    targetPort: 1024
