apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodered-deployment
    namespace: alkis-azna
    labels:
        app: nodered
        version: v1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nodered
    template:
        metadata:
            labels:
                app: nodered
                version: v1
        spec:
            containers:
                - name: node-red
                  image: nodered/node-red:latest
                  imagePullPolicy: IfNotPresent
                  securityContext:
                    runAsUser: 0
                  ports:
                    - containerPort: 1880
                  env:
                    - name: TZ
                      valueFrom:
                        secretKeyRef: 
                            name: nodered-secret
                            key: tz
                  volumeMounts:
                    - name: nodered-volume
                      mountPath: /data
                      subPath: nodered
            volumes:
              - name: nodered-volume
                persistentVolumeClaim:
                  claimName: nodered-volume-claim