apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: alkis-azna
spec:
  selector:
    app: nodered
  clusterIP: 10.124.0.7
  ports:
  - protocol: TCP
    name: tcp
    port: 1880
    targetPort: 1880