apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: alkis-azna
spec:
  selector:
    app: nodered
  clusterIP: 10.4.13.73
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880