apiVersion: v1
kind: Service
metadata:
  name: orionproxy
  namespace: alkis-azna
spec:
  selector:
    app: orionproxy
  clusterIP: 10.124.0.15
  ports:
  - protocol: TCP
    name: tcp
    port: 1027
    targetPort: 1027