apiVersion: apps/v1
kind: Deployment
metadata:
    name: keyrock-deployment
    namespace: alkis-azna
    labels:
        app: keyrock
        version: v1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keyrock
    template:
        metadata:
            labels:
                app: keyrock
                version: v1
        spec:
            containers:
            - name: fiware-keyrock
              image: fiware/idm:7.6.0
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 3005
                - containerPort: 443
              env:
                - name: DEBUG
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: debug
                - name: IDM_DB_HOST
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: db_host
                - name: IDM_DB_PORT
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: db_port
                - name: IDM_HOST
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: host
                - name: IDM_PORT
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: port
                - name: IDM_DB_PASS
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: db_pass
                - name: IDM_DB_USER
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: db_user
                - name: IDM_ADMIN_USER
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: admin_user
                - name: IDM_ADMIN_EMAIL
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: admin_email
                - name: IDM_ADMIN_PASS
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: admin_pass
                - name: IDM_PDP_LEVEL
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: pdp_level
                - name: IDM_AUTHZFORCE_ENABLED
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: authzforce_enabled
                - name: IDM_AUTHZFORCE_HOST
                  valueFrom:
                    secretKeyRef: 
                        name: keyrock-secret
                        key: authzforce_host
                - name: IDM_AUTHZFORCE_PORT
                  valueFrom:
                   secretKeyRef: 
                       name: keyrock-secret
                       key: authzforce_port


