apiVersion: v1
kind: Service
metadata:
  name: keyrock
  namespace: alkis-azna
spec:
  type: NodePort
  selector:
    app: keyrock
  clusterIP: 10.124.0.2
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 32027