apiVersion: v1
kind: Service
metadata:
  name: comet
  namespace: alkis-azna
spec:
  selector:
    app: comet
  clusterIP: 10.124.0.13
  ports:
  - protocol: TCP
    name: tcp
    port: 8666
    targetPort: 8666