apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: alkis-azna
spec:
  type: NodePort
  selector:
    app: apache
  clusterIP: 10.4.12.96
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
    #For multiple-ports we have to define the name of each port