apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    namespace: alkis-azna
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql-db
                  image: mysql:5.7.21
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 3306
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef: 
                            name: mysql-secret
                            key: root_password
                    - name: MYSQL_ROOT_HOST
                      valueFrom:
                        secretKeyRef: 
                            name: mysql-secret
                            key: root_host
                  volumeMounts:
                    - name: mysql-volume
                      mountPath: /var/lib/mysql
                      subPath: mysql
            volumes:
              - name: mysql-volume
                persistentVolumeClaim:
                  claimName: mysql-volume-claim