apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: alkis-azna
spec:
  type: NodePort
  selector:
    app: apache
  clusterIP: 10.124.0.3
  ports:
  - protocol: TCP
    name: tcp
    port: 80
    targetPort: 80
    nodePort: 32000