apiVersion: v1
kind: Service
metadata:
  name: sthcometproxy
  namespace: alkis-azna
spec:
  selector:
    app: sthcometproxy
  #clusterIP: 10.4.3.122
  ports:
  - protocol: TCP
    port: 8667
    targetPort: 8667
